### PR TITLE
Added support for the Assistant Coach type

### PR DESCRIPTION
**Pull request by jhawkzz**
Updated the group roster list to treat Assistant Coaches as leaders

MobileAppGroup.cs
-Added AssistantCoach enum value

GroupMemberAdapter.cs
-Changed 'isCoach' to 'showContactInfo'
(with Assistant Coach support, this better reflects what the value is for)

GroupRole.cs
-Added AssistantCoach enum value

GroupDetailFragment.cs
FragmentGroupDetail.axml
-Create a list of assistant coaches
-Updated 'isCoach' check with a broader 'canAdministrate' value
(which now supports being a coach OR assistant coach)
-Added Assistant Coach recycler view (uses the existing GroupMemberAdapter)
-Updated the name for the Member recycler/adapter view to be more specific so as not to conflict with the assistantCoach recycler/adapter

### CODE REVIEW

**Comment by jhawkzz** [comment]
@kkestell leadership here really, really REALLY REALLY wanted Assistant Coaches to have coach-like access in the new app.

I was as meticulous as possible to get in and add support without disrupting any of the work you've put in. I made sure to write the code exactly like you would (which is depressingly better than I normally write code ;) )

I tested every scenario to ensure nothing outside of putting Assistant Coaches up underneath the AP/Coach section changed, and I gave you a line by line overview of what I did. Hoping this is an easy approval for you! PLEASE let me know if there's anything wrong here.

**Comment by kkestell** [comment]
Thanks for the compliment. I'm flattered. Looks great! 👍

**Comment by kkestell** [comment]
Just pulled down this branch to use it as a basis for a new feature branch for some additional work on the members list, and I noticed that the `join_spacer` in `FragmentGroupDetail.axml` needs to be updated. Instead of a `app:layout_constraintTop_toBottomOf="@+id/recycler_view"` property, it should be `app:layout_constraintTop_toBottomOf="@+id/members_recycler_view"`.

Bonus points if you can figure out how to achieve the same thing without using a `join_spacer` view (e.g. just putting margins or padding on something else). I spent a little time on it and wasn't able to see a clean solution, but I'm sure one exists.

NOTE: This adds some whitespace at the very bottom of the view so that the "join" button doesn't overlap the rest of the content.

**Comment by jhawkzz** [comment]
Thanks for catching that, @kkestell! I fixed it for thoroughness, even tho it'll get merged over by your branch later.

As for doing that spacing in code, the only way I can think to off the top of my head is the replace where the `spacer` is being set to Gone would be to edit the positioning or margin of the `recyclerView`. I did _A TON_ of procedural layout on Android for the Notes feature in the app, and the takeaway is they really, really, really encourage using layouts and **not** moving things around in code, so your hunch is right--anything you do in code is going to be as many lines as it would to just use a spacer. The spacer is the way to go in my opinion.

**Pull request merged**
