### PR TITLE
CCV-525: Person Detail Formatting

### PR DESCRIPTION
**Pull request by dwee9**

### CODE REVIEW

**Comment by jhawkzz** [comment]
Does this also protect against tapping the address button when there's no address? (I see email is being checked)

**Comment by dwee9** [comment]
@jhawkzz Yes, the whole view including the button will be hidden, so it wont be clickable. I could add a check in the map method too if you would like?

**Comment by jhawkzz** [comment]
I'd just test it with someone that doesn't have an address and see whether it's necessary or not. I can update data to give you someone without an address, or you can probably just fake that in code. Let me know

**Comment by dwee9** [comment]
@jhawkzz Yup it hides it and is not clickable

**Comment by jhawkzz** [comment]
Cool! Thanks for checkin :)

**Pull request merged**
